#!/usr/bin/env python3
"""Generate idempotent D1 INSERT statements from a legacy LICENSE_STORE JSON.

The authoritative licence store is the D1 `licenses` table. Historically keys
lived in the LICENSE_STORE Worker secret (a JSON map of key -> record). This
script converts that JSON into `INSERT ... ON CONFLICT DO UPDATE` statements so
existing keys can be copied into D1 without downtime and safely re-run.

Usage:
    # Pipe the JSON straight from the secret file:
    python3 scripts/migrate-store-to-d1.py "$(grep '^LICENSE_STORE' .dev.vars | cut -d= -f2-)"
    # then apply the printed SQL:
    npx wrangler d1 execute plugin-update-server --remote --file=-

The records written use the same shape as db.insertLicense()/decodeLicense():
    key, email, name, products, status, expires, mode, max_sites, created_at, domains

LICENSE_STORE records historically carried only {products, status, expires}, so
email/name default to empty and mode/max_sites/domains to the safe defaults
('observe' / NULL / '{}'). Existing D1 rows are preserved: ON CONFLICT only
updates the fields we actually know, never clobbering telemetry-populated
domains or operator-set mode/max_sites.
"""

import json
import sys
import time


def sql_quote(value):
    """Single-quote a Python value for SQLite. None -> NULL."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main():
    argv = [a for a in sys.argv[1:]]
    fallback_email = ""
    # Optional: --email <addr> sets a default owner for records that lack one.
    if "--email" in argv:
        i = argv.index("--email")
        if i + 1 < len(argv):
            fallback_email = argv[i + 1]
            del argv[i : i + 2]

    if not argv or not argv[0].strip():
        print("error: pass the LICENSE_STORE JSON as the first argument", file=sys.stderr)
        return 1

    raw = argv[0].strip()
    try:
        store = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"error: not valid JSON: {exc}", file=sys.stderr)
        return 1
    if not isinstance(store, dict):
        print("error: LICENSE_STORE JSON must be an object of key -> record", file=sys.stderr)
        return 1

    now = int(time.time())
    lines = [
        "-- Generated by scripts/migrate-store-to-d1.py",
        f"-- Source: LICENSE_STORE JSON ({len(store)} key(s)) at {now}",
        "-- Idempotent: safe to re-run; never clobbers domains/mode/max_sites.",
        "-- Note: no BEGIN/COMMIT - D1 via wrangler rejects explicit transactions.",
    ]

    for key, rec in store.items():
        rec = rec if isinstance(rec, dict) else {}
        products = rec.get("products") or []
        status = rec.get("status") or "active"
        expires = rec.get("expires")  # may be None
        email = rec.get("email") or fallback_email
        name = rec.get("name")
        mode = rec.get("mode") or "observe"
        max_sites = rec.get("max_sites")
        domains = rec.get("domains") or {}

        lines.append(
            "INSERT INTO licenses "
            "(key, email, name, products, status, expires, mode, max_sites, created_at, domains) "
            "VALUES ({key}, {email}, {name}, {products}, {status}, {expires}, {mode}, {max_sites}, {created_at}, {domains}) "
            "ON CONFLICT(key) DO UPDATE SET "
            "  email    = CASE WHEN licenses.email = '' THEN excluded.email ELSE licenses.email END, "
            "  products = excluded.products, "
            "  status   = excluded.status, "
            "  expires  = excluded.expires "
            ";".format(
                key=sql_quote(key),
                email=sql_quote(email),
                name=sql_quote(name),
                products=sql_quote(json.dumps(products)),
                status=sql_quote(status),
                expires=sql_quote(expires),
                mode=sql_quote(mode),
                max_sites=sql_quote(max_sites),
                created_at=now,
                domains=sql_quote(json.dumps(domains)),
            )
        )

    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
